# Generated by Django 4.2.4 on 2023-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
