# Generated by Django 4.2.4 on 2023-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
